export const SERVICE_CATEGORIES = [
  'Plumbing',
  'Electrical',
  'Carpentry',
  'Cleaning',
  'Painting',
  'AC Repair',
  'Appliance Repair',
  'Pest Control',
  'Beauty & Wellness',
  'Tutoring',
  'Photography',
  'Catering',
  'Other',
];

export const GZB_AREAS = [
  'Indirapuram',
  'Vaishali',
  'Vasundhara',
  'Raj Nagar Extension',
  'Crossings Republik',
  'Kaushambi',
  'Vijay Nagar',
  'Shastri Nagar',
  'Lohia Nagar',
  'Govindpuram',
  'Pratap Vihar',
  'Shalimar Garden',
  'Surya Nagar',
  'Mohan Nagar',
  'Dundahera',
  'Dasna',
  'Arthala',
  'Bhopura',
  'Sahibabad',
  'Nehru Nagar',
];

export const SERVICE_ICONS = {
  'Plumbing': '🔧',
  'Electrical': '⚡',
  'Carpentry': '🪚',
  'Cleaning': '🧹',
  'Painting': '🖌️',
  'AC Repair': '❄️',
  'Appliance Repair': '🔌',
  'Pest Control': '🪲',
  'Beauty & Wellness': '💅',
  'Tutoring': '📚',
  'Photography': '📷',
  'Catering': '🍽️',
  'Other': '🛠️',
};

export const STATUS_COLORS = {
  pending: { bg: '#FFF8E1', text: '#F59E0B', label: 'Pending' },
  accepted: { bg: '#E8F5E9', text: '#10B981', label: 'Accepted' },
  rejected: { bg: '#FFEBEE', text: '#EF4444', label: 'Rejected' },
  completed: { bg: '#E3F2FD', text: '#3B82F6', label: 'Completed' },
  cancelled: { bg: '#FAFAFA', text: '#9E9E9E', label: 'Cancelled' },
};
